[mysqld]
datadir=C:\Users\ARUN KUMAR\OneDrive\Desktop\sportsproject\SportsBooking\mysql-data
port=3306
basedir="C:/Program Files/MySQL/MySQL Server 9.7"
secure-file-priv="C:\Users\ARUN KUMAR\OneDrive\Desktop\sportsproject\SportsBooking\uploads"
