import { useEffect, useState } from 'react';
import { cancelEquipmentReservation, fetchEquipment, fetchEquipmentReservations, reserveEquipment } from '../api.js';
import { useAuth } from '../contexts/AuthContext.jsx';
function EquipmentPage() {
  const { token } = useAuth(); const [items, setItems] = useState([]); const [reservations, setReservations] = useState([]); const [form, setForm] = useState({ equipment_id: '', quantity: 1, pickup_date: '', return_date: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { const [equipment, mine] = await Promise.all([fetchEquipment(token), fetchEquipmentReservations(token)]); setItems(equipment.data || []); setReservations(mine.data || []); } catch { setError('Unable to load equipment.'); } };
  useEffect(() => { load(); }, [token]);
  const submit = async (event) => { event.preventDefault(); setError(''); setMessage(''); const result = await reserveEquipment(token, { ...form, equipment_id: Number(form.equipment_id), quantity: Number(form.quantity) }); if (result.status !== 'success') return setError(result.message || 'Unable to reserve equipment.'); setMessage(result.message); setForm({ equipment_id: '', quantity: 1, pickup_date: '', return_date: '' }); load(); };
  const cancel = async (id) => { const result = await cancelEquipmentReservation(token, id); result.status === 'success' ? (setMessage(result.message), load()) : setError(result.message || 'Unable to cancel reservation.'); };
  return <div className="module-page"><section className="module-heading"><div><p className="eyebrow">Equipment inventory</p><h2>Book equipment</h2><p>Reserve sports equipment for your campus practice — always free.</p></div></section>{(message || error) && <div className={`alert ${message ? 'profile-success' : ''}`}>{message || error}</div>}<div className="module-grid"><section className="card"><h3>Available equipment</h3><div className="equipment-list">{items.map((item) => <article key={item.id}><div><b>{item.name}</b><span>{item.category} · {item.item_condition} condition</span></div><strong>{item.available_quantity} available</strong></article>)}</div></section><section className="card"><h3>Reserve equipment</h3><form className="profile-form" onSubmit={submit}><label>Equipment<select value={form.equipment_id} onChange={(e) => setForm({ ...form, equipment_id: e.target.value })} required><option value="">Select equipment</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.available_quantity} available)</option>)}</select></label><label>Quantity<input type="number" min="1" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} required /></label><label>Pickup date<input type="date" value={form.pickup_date} onChange={(e) => setForm({ ...form, pickup_date: e.target.value })} required /></label><label>Return date<input type="date" value={form.return_date} onChange={(e) => setForm({ ...form, return_date: e.target.value })} required /></label><button className="button">Reserve equipment</button></form></section></div><section className="card"><h3>My equipment reservations</h3>{reservations.length ? <div className="equipment-list">{reservations.map((reservation) => <article key={reservation.id}><div><b>{reservation.equipment_name} × {reservation.quantity}</b><span>{reservation.pickup_date?.slice(0, 10)} to {reservation.return_date?.slice(0, 10)} · {reservation.status}</span></div>{['pending', 'approved'].includes(reservation.status) && <button className="text-button" onClick={() => cancel(reservation.id)}>Cancel</button>}</article>)}</div> : <p className="muted">No equipment reservations yet.</p>}</section></div>;
} export default EquipmentPage;
